### ISSUE TITLE
Multi part recordings result in a crash

### ISSUE THREAD

**Issue by Auxx** [Battleman/zoomdl#26]
- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened issues for a duplicate,

**Describe the bug**
If `--count-clips` is specified then the script crashes with the following message

```
Traceback (most recent call last):
  File "zoom_dl\__main__.py", line 20, in <module>
  File "zoom_dl\__init__.py", line 18, in main
  File "zoom_dl\zoomdl.py", line 183, in download
TypeError: 'in <string>' requires string as left operand, not int
[16512] Failed to execute script __main__
```

First recording is always downloaded successfully and then it instantly crashes. That happens both on recordings with multiple parts and recording with a single part when specifying `--count-clips`.

**To Reproduce**
1. Run `$ zoomdl.exe -u "https://us02web.zoom.us/rec/share/ypEyMZiq_DhIH5WWylvjWfIfAIjEeaa80Sga_vVezRlATGqThWN0ftez5pB2iM0G" -p "SENSITIVE-PASSWORD" -f "x09" -c 0`
2. ...
3. See error

**Expected behavior**
Multiple files should be downloaded

**Logs**
Password and recording name were removed. Please contact me by e-mail (aux@hexmode.org) for password.

```
zoomdl.exe -u "https://us02web.zoom.us/rec/share/ypEyMZiq_DhIH5WWylvjWfIfAIjEeaa80Sga_vVezRlATGqThWN0ftez5pB2iM0G" -p "SENSITIVE-PASSWORD" -f "x09" -c 0 -v 0
Changing page to https://us02web.zoom.us/rec/share/ypEyMZiq_DhIH5WWylvjWfIfAIjEeaa80Sga_vVezRlATGqThWN0ftez5pB2iM0G
Checking CAPTCHA
Using password 'SENSITIVE-PASSWORD'
Changing page to https://us02web.zoom.us/rec/share/ypEyMZiq_DhIH5WWylvjWfIfAIjEeaa80Sga_vVezRlATGqThWN0ftez5pB2iM0G
Checking CAPTCHA
Metas are {'logo': {'img': 'https://us02st1.zoom.us/static/94076/image/new/ZoomLogo.png', 'link': 'https://us02web.zoom.us/', 'alt': 'Zoom Logo'}, 'isVideo': True, 'hasPermissionEdit': False, 'isRecordingHostSelf': False, 'topic': 'SENSITIVE-RECORDING-NAME-REMOVED', 'meetingId': 'G5%2FvA2b3R5q3JrTk4VvdIg%3D%3D', 'recordingId': '4a334472-75fa-4427-9a79-5e4589e0728a', 'playId': 'OJVDonbWusbRP2u_IzSRNbdPo0G-m33vRZYPU5zRkwHLFc9i_NwDsHNYF1C0khY2.MhhOqIH3nz-IIRmt', 'clipStartTime': 1589958411000, 'continueMode': 1, 'totalClips': 2, 'currentClip': 1, 'nextClipStartTime': 1589958460000, 'previousClipStartTime': -1, 'recordFileName': 'Shared screen with speaker view', 'multistream': 0, 'shareMp4Url': '', 'shareResolvtionsWidth': 0, 'shareResolvtionsHeight': 0, 'viewMp4Url': 'https://ssrweb.zoom.us/cmr/replay/2020/05/20/89671863706/1B9FEF03-66F7-479A-B726-B4E4E15BDD22/GMT20200520-070651_----------_640x360.mp4?response-content-type=video%2Fmp4&response-cache-control=max-age%3D0%2Cs-maxage%3D86400&data=02015e8f1bb59cbd25125430d49077d48adca133361d1097b833496608295f37&s001=yes&cid=us02&fid=h29vuerTZROrhZzOjALibghECtjxa5avJfCwv_7I_IcIcB9WDSWu_PnEIzzG8a7nOXrT1ljCwFYZY2Ht.D9qmkr7pb891qhR6&s002=ZK4qhrQdVb7RjYGVs0diTjpXbsy7PYmdjooSn1iYn2UaDQuqDXHSxd3flFzFg082SrA9mw.Q-fypMLb_2vxo3Vg&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHBzOi8vc3Nyd2ViLnpvb20udXMvY21yL3JlcGxheS8yMDIwLzA1LzIwLzg5NjcxODYzNzA2LzFCOUZFRjAzLTY2RjctNDc5QS1CNzI2LUI0RTRFMTVCREQyMi9HTVQyMDIwMDUyMC0wNzA2NTFfLS0tLS0tLS0tLV82NDB4MzYwLm1wND9yZXNwb25zZS1jb250ZW50LXR5cGU9dmlkZW8lMkZtcDQmcmVzcG9uc2UtY2FjaGUtY29udHJvbD1tYXgtYWdlJTNEMCUyQ3MtbWF4YWdlJTNEODY0MDAmZGF0YT0wMjAxNWU4ZjFiYjU5Y2JkMjUxMjU0MzBkNDkwNzdkNDhhZGNhMTMzMzYxZDEwOTdiODMzNDk2NjA4Mjk1ZjM3JnMwMDE9eWVzJmNpZD11czAyJmZpZD1oMjl2dWVyVFpST3JoWnpPakFMaWJnaEVDdGp4YTVhdkpmQ3d2XzdJX0ljSWNCOVdEU1d1X1BuRUl6ekc4YTduT1hyVDFsakN3RllaWTJIdC5EOXFta3I3cGI4OTFxaFI2JnMwMDI9Wks0cWhyUWRWYjdSallHVnMwZGlUanBYYnN5N1BZbWRqb29TbjFpWW4yVWFEUXVxRFhIU3hkM2ZsRnpGZzA4MlNyQTltdy5RLWZ5cE1MYl8ydnhvM1ZnIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjAwOTQyMjAyfX19XX0_&Signature=fggxOA8GE99Kn~cePJxpHVLA7tO1Hwa7c6KOSNvweQka~ELhQxhXRLM~EKjqapaWpbxdqLGhCYd~O~uv72scmSJ3SAGogYxTvGVQqRx0UWM9Nt0TlCDpLOLqV04bPUS0Ql139Ec5Rxo74ylXYq4jJVtZtmGuMz7mZJt22xgrEJlSNzvX-c9hheBL4xqQRrqGbQ4Cp1akqjboK4ZUYno7kLpgPE1zgFOSo9VCuJaJyGPm-FPysr82QWAIAcy1Ul3WUrU1M6TQlbKtv7TYdlosrWf-XGnq7M726xsAH9tEcgXzNA960PiAD5cqZo8N~O~s1HNroSYiSgNDMhrPIwsaGA__&Key-Pair-Id=APKAJFHNSLHYCGFYQGIA', 'gallaryMp4Url': '', 'offsetStart': 0, 'offsetEnd': 0, 'viewResolvtionsWidth': 640, 'viewResolvtionsHeight': 360, 'shareVideoId': '', 'transcriptList': [], 'chatList': [], 'chapterSections': [], 'chapterUrl': '/rec/play/vtt?fid=h29vuerTZROrhZzOjALibghECtjxa5avJfCwv_7I_IcIcB9WDSWu_PnEIzzG8a7nOXrT1ljCwFYZY2Ht.D9qmkr7pb891qhR6&action=play', 'ccUrl': '', 'transcriptUrl': '', 'disableDownload': True, 'clipDownload': True, 'numOfClipFile': 2, 'fileSize': '312 KB', 'playCheckInterval': 60, 'clusterId': 'us02', 'playCheckId': 'h29vuerTZROrhZzOjALibghECtjxa5avJfCwv_7I_IcIcB9WDSWu_PnEIzzG8a7nOXrT1ljCwFYZY2Ht.D9qmkr7pb891qhR6'}
Found name is SENSITIVE-RECORDING-NAME-REMOVED, extension is mp4
Full filepath is F:\blog.benchandbowl.com\training\wheat\x09.mp4
Downloading 'F:\blog.benchandbowl.com\training\wheat\x09.mp4'...
[################################] 313/313 - 00:00:00
Done!
Traceback (most recent call last):
  File "zoom_dl\__main__.py", line 20, in <module>
  File "zoom_dl\__init__.py", line 18, in main
  File "zoom_dl\zoomdl.py", line 183, in download
TypeError: 'in <string>' requires string as left operand, not int
[14280] Failed to execute script __main__
```
**Versions (please complete the following information):**
 - OS: Windows 10 2004 (19041.508)
 - Python Version: unknown

**Comment by Battleman** [comment]
OK, I think I found the problem. I finally got my hands on a multi-clips recording.
I think #25 (due to #24) changed a _slight_ detail: metadata are somehow interpreted (integers become integers, and not str). So I suppose this is when the issue appeared. Fix was easy, it's in the upcoming release. I'll close this issue as I believe it's fixed. Don't hesitate to reopen if not.
