### ISSUE TITLE
Bug: Windows exe build tqdm module missing

### ISSUE THREAD

**Issue by Stankye** [Battleman/zoomdl#29]
## PLEASE FILL IN THE TEMPLATE BELOW, DON'T SIMPLY ERASE EVERYTHING. ISSUES NOT FOLLOWING THIS TEMPLATE WILL NOT BE CONSIDERED.
**Prerequisite** Tick (`[ ] --> [x]`) if you have done the following:
- [x] I have updated to the latest version,
- [ ] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened issues for a duplicate,

**Describe the bug**
ModuleNotFoundError: No module named 'tqdm' on windows build 

**To Reproduce**
Download 2020.10.23, run in Windows 10, Python 3.8.3

**Expected behavior**
Run, maybe show a help prompt or something

**Logs**
```
Traceback (most recent call last):
  File "zoom_dl\__main__.py", line 17, in <module>
  File "c:\users\olivi\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "zoom_dl\__init__.py", line 5, in <module>
  File "c:\users\olivi\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "zoom_dl\zoomdl.py", line 9, in <module>
ModuleNotFoundError: No module named 'tqdm'
[16076] Failed to execute script __main__
```
**Versions (please complete the following information):**
 - OS: Windows 10
 - Python Version: 3.8.3

**Comment by Battleman** [comment]
That's why I don't like programming for window ^.^
It _should_ be fixed now. Can you confirm executable for 2020.10.23 works?

**Comment by Stankye** [comment]
Updated bin is now running.  Thanks!
