### ISSUE TITLE
Recordings with a slash (/) in the title crash

### ISSUE THREAD

**Issue by Battleman** [Battleman/zoomdl#31]
**Prerequisite** Tick (`[ ] --> [x]`) if you have done the following:
- [x] I have updated to the latest version,
- [x] (If applicable) I have ensured the password is correct with the flag `-v 0`,
- [x] I have searched the opened issues for a duplicate,

**Describe the bug**
When downloading a video with a forward slash in the title, zoomdl raises a FileNotFoundError.

**To Reproduce**
1. Enter command for video download

**Expected behavior**
Video should be downloaded, with a name maybe modified to make it safe

**Screenshots**

**Logs**
Please add below the output of the command you launched, with the `-v 0` flag.
Remember to edit out the password if it is confidential!

```
zoomdl -u "https://us02web.zoom.us/rec/share/REDACTED" -p 'REDACTED' -v 0
Using standard Windows UA
Changing page to https://us02web.zoom.us/rec/share/REDACTED
Checking CAPTCHA
Using password 'REDACTED'
Changing page to https://us02web.zoom.us/rec/share/REDACTED
Checking CAPTCHA
Metas are {'logo': {'img': 'https://us02st1.zoom.us/static/94107/image/new/ZoomLogo.png', 'link': 'https://us02web.zoom.us/', 'alt': 'Zoom Logo'}, 'isVideo': True, 'hasPermissionEdit': False, 'isRecordingHostSelf': False, 'topic': 'CS/IT - CN', 'meetingId': 'YSKiyfx7TQiDn8jbuWjD5w%3D%3D', 'recordingId': 'b58cd070-04c3-45c5-94b3-b49d6b41537a', 'playId': 'YE4f_0xH1J5rKeolj2EGKnwfGgd8cqCdS2Tt_GZ1OGiTq1d8R4KyrpK6RFGHxmdG.pwZjVbzo413mIhmt', 'clipStartTime': 1601382217000, 'continueMode': 1, 'totalClips': 2, 'currentClip': 1, 'nextClipStartTime': 1601383719000, 'previousClipStartTime': -1, 'recordFileName': 'Shared screen with speaker view', 'multistream': 0, 'shareMp4Url': '', 'shareResolvtionsWidth': 0, 'shareResolvtionsHeight': 0, 'viewMp4Url': 'https://ssrweb.zoom.us/cmr/replay/2020/09/29/REDACTED/GMT20200929-122337_CS-IT---CN_1920x1080.mp4?response-content-type=video%2Fmp4&response-cache-control=max-age%3D0%2Cs-maxage%3D86400&data=cleaned&Policy=cleaned&Signature=cleaned&Key-Pair-Id=APKAJFHNSLHYCGFYQGIA', 'gallaryMp4Url': '', 'offsetStart': 0, 'offsetEnd': 0, 'viewResolvtionsWidth': 1920, 'viewResolvtionsHeight': 1080, 'shareVideoId': '', 'transcriptList': [], 'chatList': [], 'chapterSections': [], 'chapterUrl': '/rec/play/vtt?fid=r8PKP0jXuM0NRNvfCXi5iV2FV2TZerU_n3hbopp2-U5G8BggxuxjX5K6DKBnL4G7ZPnjUvs7dwFBtOfS.oPdwGs6y_NXezl1y&action=play', 'ccUrl': '', 'transcriptUrl': '', 'disableDownload': True, 'clipDownload': True, 'numOfClipFile': 1, 'fileSize': '43 MB', 'playCheckInterval': 60, 'clusterId': 'us02', 'playCheckId': 'r8PKP0jXuM0NRNvfCXi5iV2FV2TZerU_n3hbopp2-U5G8BggxuxjX5K6DKBnL4G7ZPnjUvs7dwFBtOfS.oPdwGs6y_NXezl1y', 'polls': []}
Found name is CS/IT_-_CN, extension is mp4
Full filepath is /home/battleman/CS/IT_-_CN.mp4  <--- ERROR HERE
Downloading 'IT_-_CN.mp4'...
Traceback (most recent call last):
  File "/storage/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/storage/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/bin/zoomdl/__main__.py", line 20, in <module>
  File "/usr/local/bin/zoomdl/zoom_dl/__init__.py", line 18, in main
  File "/usr/local/bin/zoomdl/zoom_dl/zoomdl.py", line 192, in download
  File "/usr/local/bin/zoomdl/zoom_dl/zoomdl.py", line 121, in download_vid
FileNotFoundError: [Errno 2] No such file or directory: '/home/battleman/CS/IT_-_CN.mp4'

```
**Versions (please complete the following information):**
 - OS: Debian stable
 - Python Version: 3.7.6

**Additional context**
The problem also probably affects windows, with backward slashes (\).

**Comment by Battleman** [comment]
Fixed in 02a4bd3
